N_SEGMENTS = 5
FEDERATED_TRAINER_HOST = "http://localhost:8080"
ETA = 1.5
REGISTRATION_ENABLE = False
ACTIVE_ENCRYPTION = False
DATASETS_DIR = "./dataset"
KEY_LENGTH = 1024
DB_ENGINE = 'sqlite:///data_owner.db'